### ISSUE TITLE
✨[Feature] 보컬 - 데이터룸 api에 보고서 상태 추가 및 전송 데이터 기준 변경

### ISSUE THREAD

**Issue by besyia0k0** [42connected/polar-be#427]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [ ] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 데이터룸에 보내주는 데이터의 기준을 `'멘토링 완료'`로 수정합니다.

## 📝 기능 상세 내용

현재 데이터룸에 보이는 멘토링 로그의 기준은 `'멘토링 완료' && '보고서 작성 완료'` 입니다.
보고서 작성 후 수정 기능이 추가되면서, 데이터룸에서 `멘토링이 완료되었으나 보고서가 작성되지 않았거나 작성중인 상태`인 로그도 볼 수 있어야 한다는 점이 대두되었습니다.
- 따라서, 데이터룸에 보내주는 멘토링 로그의 기준을 `'멘토링 완료'`로 변경합니다.
- 또한, 멘토링 로그 api 당 `보고서 상태`를 추가하여, 다음과 같은 디자인(가안)을 구현할 수 있도록 합니다.

>**송피디님 요청**
확정건 관계없이 모두 검색되면 좋겠습니다.
보고서 확정건을 금액으로 확인하는 것이 아닌 하나의 플래그가 있으면 좋겠습니다.
확정 비확정? 정도

![image](https://user-images.githubusercontent.com/71981659/202651869-38ce536c-b5b8-4bde-b12b-e4940c97a61e.png)

## ✅ TODO

- [ ] 멘토링 로그 당 api에 현재 보고서 상태를 추가합니다.
- [ ] 데이터룸에서 보내주는 멘토링 로그의 기준을 `'멘토링 완료'`로 변경합니다.
